# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
  This recipe will use the `finalizeDsl` block to add a build type programmatically.
  """

[agpVersion]
min = "9.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "extraVerifyRecipe",
    "assembleExtra"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "Themes/DSL",
    "APIs/DslLifecycle.finalizeDsl()",
    "Call chains/androidComponents.finalizeDsl {}"
]
