# optional (if present and non-blank) name to use in the index
indexName = ""
# optional (if present and non-blank) folder name to use when converting recipe in RELEASE mode
destinationFolder = ""

description ="""
   This sample shows how to get and update the variant output using the variant API.
  """

[agpVersion]
min = "9.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    ":app:checkFlavor1DebugMergedManifest",
    ":app:checkFlavor2ReleaseMergedManifest"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "APIs/AndroidComponentsExtension.onVariants()",
    "APIs/AndroidComponentsExtension.selector()",
    "APIs/ApplicationVariant.outputs",
    "APIs/Artifacts.get()",
    "APIs/Component.artifacts",
    "APIs/SingleArtifact.MERGED_MANIFEST",
    "APIs/VariantOutput.versionCode",
    "APIs/VariantOutput.versionName",
    "APIs/VariantOutputConfiguration.outputType",
    "APIs/VariantOutputConfiguration.OutputType.SINGLE",
    "APIs/VariantSelector.all()",
    "APIs/VariantSelector.withFlavor()",
    "Call chains/androidComponents.onVariants {}",
    "Call chains/androidComponents.selector().all()",
    "Call chains/androidComponents.selector().withFlavor()",
    "Call chains/variant.artifacts.get()",
]
