[versions]
androidGradlePlugin = "9.0.0"
kotlin = "2.1.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


